# Generated by Django 4.1.2 on 2022-10-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_critic",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
