# Generated by Django 4.1.2 on 2022-10-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genre", "0002_remove_genre_movie"),
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(related_name="movies", to="genre.genre"),
        ),
    ]
