# Generated by Django 4.1.2 on 2022-10-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genre", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="movie",
        ),
    ]
